# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up GOPRIVATE
      run: go env -w GOPRIVATE="github.com/xxtea01"

    - name: Set up git
      # 这里还是需要换个用户名
      run: git config --global url."https://${{ secrets.USERNAME }}:${{ secrets.ACCESS_TOKEN }}@github.com".insteadof "https://github.com"
    
    - name: Build
      run: make build

#    - name: Test
#      run: make test

    - name: Deploy to Vultr
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: root
        password: ${{ secrets.DEV_SERVER_PASSPHRASE }}
        source: "bin/xxt-rpc,config/dev,migrations,Makefile"
        target: "xxt-rpc"

    - name: Migrate
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: root
        password: ${{ secrets.DEV_SERVER_PASSPHRASE }}
        script: |
          cd /root/xxt-rpc && make migrate-dev

    - name: Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: root
        password: ${{ secrets.DEV_SERVER_PASSPHRASE }}
        script: |
          curl -sS http://localhost:10201/status
          sudo supervisorctl restart xxt-rpc
          sleep 5